CREATE TABLE IF NOT EXISTS sales_prospects (
  prospect_id TEXT PRIMARY KEY,
  source_key TEXT NOT NULL UNIQUE,
  external_ref TEXT,
  business_name TEXT NOT NULL,
  owner_first_name TEXT,
  contact_name TEXT,
  contact_email TEXT,
  email_permission BOOLEAN NOT NULL DEFAULT FALSE,
  email_suppressed_at TIMESTAMPTZ,
  email_suppression_reason TEXT,
  smartlead_lead_id TEXT,
  smartlead_campaign_id TEXT,
  smartlead_status TEXT,
  last_email_event_at TIMESTAMPTZ,
  lead_delivery_email TEXT,
  phone_e164 TEXT NOT NULL,
  website_url TEXT,
  business_category TEXT,
  competitor_name TEXT,
  timezone TEXT,
  permission_granted BOOLEAN NOT NULL DEFAULT FALSE,
  permission_recorded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  suppressed BOOLEAN NOT NULL DEFAULT FALSE,
  suppression_reason TEXT,
  suppressed_at TIMESTAMPTZ,
  do_not_call BOOLEAN NOT NULL DEFAULT FALSE,
  do_not_call_at TIMESTAMPTZ,
  queue_position BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  status TEXT NOT NULL DEFAULT 'queued',
  last_outcome TEXT,
  last_outcome_at TIMESTAMPTZ,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  imported_by_admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  row_version INTEGER NOT NULL DEFAULT 1,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS sales_prospects_external_ref_unique_idx
  ON sales_prospects (external_ref)
  WHERE external_ref IS NOT NULL AND external_ref <> '';

CREATE INDEX IF NOT EXISTS sales_prospects_queue_idx
  ON sales_prospects (status, queue_position ASC);

CREATE INDEX IF NOT EXISTS sales_prospects_eligibility_idx
  ON sales_prospects (permission_granted, suppressed, do_not_call, queue_position ASC);

CREATE INDEX IF NOT EXISTS sales_prospects_phone_idx
  ON sales_prospects (phone_e164);

CREATE INDEX IF NOT EXISTS sales_prospects_contact_email_idx
  ON sales_prospects (LOWER(contact_email))
  WHERE contact_email IS NOT NULL AND contact_email <> '';

CREATE TABLE IF NOT EXISTS sales_demo_profiles (
  demo_profile_id TEXT PRIMARY KEY,
  prospect_id TEXT NOT NULL UNIQUE REFERENCES sales_prospects(prospect_id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'not_prepared',
  source_website_url TEXT,
  normalized_website_url TEXT,
  website_origin TEXT,
  website_hostname TEXT,
  business_name TEXT,
  preview_summary TEXT,
  demo_bundle_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  scrape_page_count INTEGER NOT NULL DEFAULT 0,
  scrape_pages_json JSONB NOT NULL DEFAULT '[]'::jsonb,
  extraction_version TEXT,
  build_attempts INTEGER NOT NULL DEFAULT 0,
  failure_code TEXT,
  failure_message TEXT,
  build_started_at TIMESTAMPTZ,
  build_completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sales_demo_profiles_status_expiry_idx
  ON sales_demo_profiles (status, expires_at ASC);

CREATE INDEX IF NOT EXISTS sales_demo_profiles_prospect_status_idx
  ON sales_demo_profiles (prospect_id, status);

CREATE TABLE IF NOT EXISTS sales_demo_jobs (
  sales_demo_job_id TEXT PRIMARY KEY,
  prospect_id TEXT NOT NULL REFERENCES sales_prospects(prospect_id) ON DELETE CASCADE,
  status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 3,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked_at TIMESTAMPTZ,
  locked_by TEXT,
  completed_at TIMESTAMPTZ,
  last_error_code TEXT,
  last_error_message TEXT,
  requested_by_admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS sales_demo_jobs_active_prospect_idx
  ON sales_demo_jobs (prospect_id)
  WHERE status IN ('queued', 'leased');

CREATE INDEX IF NOT EXISTS sales_demo_jobs_claim_idx
  ON sales_demo_jobs (status, available_at ASC, created_at ASC);

CREATE TABLE IF NOT EXISTS sales_call_sessions (
  sales_call_id TEXT PRIMARY KEY,
  prospect_id TEXT NOT NULL REFERENCES sales_prospects(prospect_id) ON DELETE RESTRICT,
  admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  state TEXT NOT NULL DEFAULT 'created',
  conference_id TEXT,
  conference_name TEXT,
  operator_call_control_id TEXT,
  operator_leg_id TEXT,
  operator_session_id TEXT,
  prospect_call_control_id TEXT,
  prospect_leg_id TEXT,
  prospect_session_id TEXT,
  ai_telnyx_call_control_id TEXT,
  ai_telnyx_leg_id TEXT,
  ai_telnyx_session_id TEXT,
  openai_call_id TEXT,
  ai_state TEXT,
  provider_error_code TEXT,
  provider_error_message TEXT,
  outcome TEXT,
  outcome_notes TEXT,
  outcome_recorded_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  connected_at TIMESTAMPTZ,
  demo_started_at TIMESTAMPTZ,
  demo_ended_at TIMESTAMPTZ,
  ended_at TIMESTAMPTZ,
  idempotency_key TEXT,
  metadata_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS sales_call_sessions_admin_idempotency_idx
  ON sales_call_sessions (admin_user_id, idempotency_key)
  WHERE admin_user_id IS NOT NULL AND idempotency_key IS NOT NULL AND idempotency_key <> '';

CREATE INDEX IF NOT EXISTS sales_call_sessions_prospect_created_idx
  ON sales_call_sessions (prospect_id, created_at DESC);

CREATE INDEX IF NOT EXISTS sales_call_sessions_state_updated_idx
  ON sales_call_sessions (state, updated_at DESC);

CREATE INDEX IF NOT EXISTS sales_call_sessions_conference_idx
  ON sales_call_sessions (conference_id)
  WHERE conference_id IS NOT NULL;

CREATE TABLE IF NOT EXISTS sales_call_events (
  sales_call_event_id BIGSERIAL PRIMARY KEY,
  sales_call_id TEXT NOT NULL REFERENCES sales_call_sessions(sales_call_id) ON DELETE CASCADE,
  provider TEXT NOT NULL,
  event_id TEXT NOT NULL,
  type TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  processing_status TEXT NOT NULL DEFAULT 'received',
  processing_attempts INTEGER NOT NULL DEFAULT 0,
  processing_token TEXT,
  processing_started_at TIMESTAMPTZ,
  processed_at TIMESTAMPTZ,
  last_error_code TEXT,
  last_error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider, event_id)
);

-- Keep this migration safe when an earlier draft already created the event table.
-- Historical rows predate durable processing and are treated as completed so a
-- deployment never replays old provider calls.
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS processing_status TEXT;
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS processing_attempts INTEGER;
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS processing_token TEXT;
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS processing_started_at TIMESTAMPTZ;
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS processed_at TIMESTAMPTZ;
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS last_error_code TEXT;
ALTER TABLE sales_call_events
  ADD COLUMN IF NOT EXISTS last_error_message TEXT;

UPDATE sales_call_events
SET processing_status = 'processed',
    processing_attempts = COALESCE(processing_attempts, 0),
    processed_at = COALESCE(processed_at, created_at)
WHERE processing_status IS NULL;

ALTER TABLE sales_call_events
  ALTER COLUMN processing_status SET DEFAULT 'received',
  ALTER COLUMN processing_status SET NOT NULL,
  ALTER COLUMN processing_attempts SET DEFAULT 0,
  ALTER COLUMN processing_attempts SET NOT NULL;

CREATE INDEX IF NOT EXISTS sales_call_events_call_occurred_idx
  ON sales_call_events (sales_call_id, occurred_at ASC);

CREATE INDEX IF NOT EXISTS sales_call_events_processing_idx
  ON sales_call_events (processing_status, processing_started_at ASC)
  WHERE processing_status <> 'processed';

CREATE TABLE IF NOT EXISTS sales_followup_jobs (
  sales_followup_job_id TEXT PRIMARY KEY,
  prospect_id TEXT NOT NULL REFERENCES sales_prospects(prospect_id) ON DELETE CASCADE,
  sales_call_id TEXT REFERENCES sales_call_sessions(sales_call_id) ON DELETE SET NULL,
  outcome TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'queued',
  attempts INTEGER NOT NULL DEFAULT 0,
  max_attempts INTEGER NOT NULL DEFAULT 5,
  available_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  locked_at TIMESTAMPTZ,
  locked_by TEXT,
  completed_at TIMESTAMPTZ,
  provider_result_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  last_error_code TEXT,
  last_error_message TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS sales_followup_jobs_active_outcome_idx
  ON sales_followup_jobs (prospect_id, sales_call_id, outcome)
  WHERE status IN ('queued', 'leased');

CREATE INDEX IF NOT EXISTS sales_followup_jobs_claim_idx
  ON sales_followup_jobs (status, available_at ASC, created_at ASC);

CREATE TABLE IF NOT EXISTS sales_email_events (
  sales_email_event_id BIGSERIAL PRIMARY KEY,
  provider TEXT NOT NULL,
  event_id TEXT NOT NULL,
  prospect_id TEXT REFERENCES sales_prospects(prospect_id) ON DELETE SET NULL,
  email TEXT,
  type TEXT NOT NULL,
  payload_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  occurred_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (provider, event_id)
);

CREATE INDEX IF NOT EXISTS sales_email_events_prospect_occurred_idx
  ON sales_email_events (prospect_id, occurred_at DESC);

CREATE TABLE IF NOT EXISTS sales_prospect_notes (
  sales_prospect_note_id TEXT PRIMARY KEY,
  prospect_id TEXT NOT NULL REFERENCES sales_prospects(prospect_id) ON DELETE CASCADE,
  sales_call_id TEXT REFERENCES sales_call_sessions(sales_call_id) ON DELETE SET NULL,
  body TEXT NOT NULL,
  created_by_admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sales_prospect_notes_prospect_created_idx
  ON sales_prospect_notes (prospect_id, created_at DESC);

CREATE TABLE IF NOT EXISTS sales_signup_invitations (
  invitation_id TEXT PRIMARY KEY,
  prospect_id TEXT NOT NULL REFERENCES sales_prospects(prospect_id) ON DELETE RESTRICT,
  sales_call_id TEXT REFERENCES sales_call_sessions(sales_call_id) ON DELETE SET NULL,
  token_hash TEXT NOT NULL UNIQUE,
  creation_idempotency_hash TEXT NOT NULL UNIQUE,
  creation_request_hash TEXT NOT NULL,
  safe_prefill_json JSONB NOT NULL DEFAULT '{}'::jsonb,
  status TEXT NOT NULL DEFAULT 'pending',
  delivery_email TEXT NOT NULL,
  expires_at TIMESTAMPTZ NOT NULL,
  sent_at TIMESTAMPTZ,
  opened_at TIMESTAMPTZ,
  consumed_at TIMESTAMPTZ,
  submitted_at TIMESTAMPTZ,
  converted_tenant_key TEXT,
  revoked_at TIMESTAMPTZ,
  created_by_admin_user_id BIGINT REFERENCES admin_users(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS sales_signup_invitations_prospect_created_idx
  ON sales_signup_invitations (prospect_id, created_at DESC);

CREATE INDEX IF NOT EXISTS sales_signup_invitations_status_expiry_idx
  ON sales_signup_invitations (status, expires_at ASC);

CREATE TABLE IF NOT EXISTS sales_idempotency_keys (
  sales_idempotency_id BIGSERIAL PRIMARY KEY,
  admin_user_id BIGINT NOT NULL REFERENCES admin_users(id) ON DELETE CASCADE,
  scope TEXT NOT NULL,
  idempotency_key TEXT NOT NULL,
  request_hash TEXT NOT NULL,
  state TEXT NOT NULL DEFAULT 'processing',
  response_status INTEGER,
  response_json JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  completed_at TIMESTAMPTZ,
  expires_at TIMESTAMPTZ NOT NULL DEFAULT (NOW() + INTERVAL '24 hours'),
  UNIQUE (admin_user_id, scope, idempotency_key)
);

CREATE INDEX IF NOT EXISTS sales_idempotency_keys_expiry_idx
  ON sales_idempotency_keys (expires_at ASC);

CREATE TABLE IF NOT EXISTS sales_operator_settings (
  admin_user_id BIGINT PRIMARY KEY REFERENCES admin_users(id) ON DELETE CASCADE,
  telnyx_telephony_credential_id TEXT,
  display_name TEXT,
  caller_id_number TEXT,
  active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
